language: "python"

sudo: required
dist: xenial

python: "3.8"

branches:
  only:
    - master

before_install:
  - "sudo apt-get install -y language-pack-nl"
  - "pip install --no-cache-dir poetry"

install:
  - "poetry install"

script:
  - "poetry run pytest --cov=bot ."
  - "poetry run black --check bot.py test_bot_offline.py"

notifications:
  email:
    on_success: "never"
    on_failure: "always"
